services:
  - type: web
    name: stock-market-analysis
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/app.py
    envVars:
      - key: PORT
        value: 8000